name: Deploy to Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг для клонирования репозитория
      - name: Checkout code
        uses: actions/checkout@v2

      # Шаг для настройки SSH
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Шаг для деплоя на сервер
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            # Переходим в директорию проекта
            cd api/AttendanceApi || exit

            # Получаем последние изменения из репозитория
            git pull origin main || exit

            # Останавливаем и удаляем старые контейнеры
            cd
            cd api
            docker-compose down || exit

            # Собираем и запускаем контейнеры с новыми изменениями
            docker-compose up -d --build || exit

            # Сообщение об успешном деплое
            echo "Deployment successful!"
          EOF

